version: '3.0'

services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5001:80
    expose:
      - 5001
  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 5000:80