version: '3.0'

services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"